// <auto-generated />
using System;
using Michael.ProductApiApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Michael.ProductApiApp.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20190823033644_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Michael.ProductApiApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID");

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.Property<int>("ParentID");

                    b.Property<int>("ViewOrder");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Michael.ProductApiApp.Models.Goods", b =>
                {
                    b.Property<int>("GoodsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BarCode");

                    b.Property<int>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("GoodsName");

                    b.Property<string>("GoodsSN");

                    b.Property<string>("Img");

                    b.Property<DateTime>("InputTime");

                    b.Property<bool>("IsReal");

                    b.Property<decimal>("MarketPrice");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<bool>("OnSale");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("SalePrice");

                    b.HasKey("GoodsID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Michael.ProductApiApp.Models.Goods", b =>
                {
                    b.HasOne("Michael.ProductApiApp.Models.Category", "Category")
                        .WithMany("Goodses")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
